=== G-Robson26/Aion-2.7-Galaxy-Emu/GameServer/data/static_data/stats/stats.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
		This file is part of Aion X Emu <aionxemu.com>.

		This is free software: you can redistribute it and/or modify
		it under the terms of the GNU Lesser Public License as published by
		the Free Software Foundation, either version 3 of the License, or
		(at your option) any later version.

		This software is distributed in the hope that it will be useful,
		but WITHOUT ANY WARRANTY; without even the implied warranty of
		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
		GNU Lesser Public License for more details.

		You should have received a copy of the GNU Lesser Public License
		along with this software.  If not, see <http://www.gnu.org/licenses/>.
	-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
	<xs:include schemaLocation="../global_types.xsd"/>
	<xs:include schemaLocation="../import.xsd"/>
	<xs:element name="player_stats_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="player_stats" type="playerStatsTemplateType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="summon_stats_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="summon_stats" type="summonStatsTemplateType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="playerStatsTemplateType">
		<xs:sequence>
			<xs:element name="stats_template" type="playerStatsTemplate" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="class" type="playerClass" use="required"/>
		<xs:attribute name="level" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:complexType name="playerStatsTemplate">
		<xs:complexContent>
			<xs:extension base="statsTemplate">
				<xs:attribute name="power" type="xs:int" use="required"/>
				<xs:attribute name="health" type="xs:int" use="required"/>
				<xs:attribute name="agility" type="xs:int" use="required"/>
				<xs:attribute name="accuracy" type="xs:int" use="required"/>
				<xs:attribute name="knowledge" type="xs:int" use="required"/>
				<xs:attribute name="will" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="summonStatsTemplateType">
		<xs:sequence>
			<xs:element name="stats_template" type="summonStatsTemplate" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="npc_id_light" type="xs:int"/>
		<xs:attribute name="npc_id_dark" type="xs:int"/>
		<xs:attribute name="level" type="xs:byte" use="required"/>
	</xs:complexType>
	<xs:complexType name="summonStatsTemplate">
		<xs:complexContent>
			<xs:extension base="statsTemplate">
				<xs:attribute name="pdefense" type="xs:int" use="required"/>
				<xs:attribute name="mresist" type="xs:int" use="required"/>
				<xs:attribute name="mcrit" type="xs:int"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="statsTemplate" abstract="true">
		<xs:attribute name="maxHp" type="xs:int" use="required"/>
		<xs:attribute name="maxMp" type="xs:int"/>
		<xs:attribute name="walk_speed" type="xs:float"/>
		<xs:attribute name="run_speed" type="xs:float"/>
		<xs:attribute name="fly_speed" type="xs:float"/>
		<xs:attribute name="attack_speed" type="xs:float"/>
		<xs:attribute name="evasion" type="xs:int"/>
		<xs:attribute name="block" type="xs:int"/>
		<xs:attribute name="parry" type="xs:int"/>
		<xs:attribute name="main_hand_attack" type="xs:int"/>
		<xs:attribute name="main_hand_accuracy" type="xs:int"/>
		<xs:attribute name="main_hand_crit_rate" type="xs:int"/>
		<xs:attribute name="magic_accuracy" type="xs:int"/>
		<xs:attribute name="boost_heal" type="xs:int"/>
	</xs:complexType>
</xs:schema>

=== G-Robson26/Aion-2.7-Galaxy-Emu/GameServer/data/static_data/stats/player/cleric-templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<player_stats_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../stats.xsd">

	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="CLERIC" level="9">
		<stats_template maxHp="576" maxMp="1215"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="142" block="142" parry="142"
		                main_hand_attack="18" main_hand_accuracy="242" main_hand_crit_rate="1"
		                magic_accuracy="128" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="CLERIC" level="10">
		<stats_template maxHp="628" maxMp="1320"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="155" block="155" parry="155"
		                main_hand_attack="18" main_hand_accuracy="250" main_hand_crit_rate="1"
		                magic_accuracy="142" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="CLERIC" level="11">
		<stats_template maxHp="681" maxMp="1425"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="167" block="167" parry="167"
		                main_hand_attack="18" main_hand_accuracy="258" main_hand_crit_rate="1"
		                magic_accuracy="156" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="CLERIC" level="12">
		<stats_template maxHp="737" maxMp="1531"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="179" block="179" parry="179"
		                main_hand_attack="18" main_hand_accuracy="266" main_hand_crit_rate="1"
		                magic_accuracy="171" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="CLERIC" level="13">
		<stats_template maxHp="794" maxMp="1636"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="192" block="192" parry="192"
		                main_hand_attack="18" main_hand_accuracy="274" main_hand_crit_rate="1"
		                magic_accuracy="185" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="CLERIC" level="14">
		<stats_template maxHp="853" maxMp="1741"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="204" block="204" parry="204"
		                main_hand_attack="18" main_hand_accuracy="282" main_hand_crit_rate="1"
		                magic_accuracy="199" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="CLERIC" level="15">
		<stats_template maxHp="915" maxMp="1846"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="217" block="217" parry="217"
		                main_hand_attack="18" main_hand_accuracy="290" main_hand_crit_rate="1"
		                magic_accuracy="213" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="CLERIC" level="16">
		<stats_template maxHp="977" maxMp="1951"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="229" block="229" parry="229"
		                main_hand_attack="18" main_hand_accuracy="298" main_hand_crit_rate="1"
		                magic_accuracy="228" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="CLERIC" level="17">
		<stats_template maxHp="1042" maxMp="2057"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="241" block="241" parry="241"
		                main_hand_attack="18" main_hand_accuracy="306" main_hand_crit_rate="1"
		                magic_accuracy="242" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="CLERIC" level="18">
		<stats_template maxHp="1109" maxMp="2162"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="254" block="254" parry="254"
		                main_hand_attack="18" main_hand_accuracy="314" main_hand_crit_rate="1"
		                magic_accuracy="256" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="CLERIC" level="19">
		<stats_template maxHp="1177" maxMp="2267"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="266" block="266" parry="266"
		                main_hand_attack="18" main_hand_accuracy="322" main_hand_crit_rate="1"
		                magic_accuracy="270" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 11/2009 at US Retail -->
	<player_stats class="CLERIC" level="20">
		<stats_template maxHp="1248" maxMp="2373"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="279" block="279" parry="279"
		                main_hand_attack="18" main_hand_accuracy="330" main_hand_crit_rate="1"
		                magic_accuracy="285" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 11/2009 at US Retail -->
	<player_stats class="CLERIC" level="21">
		<stats_template maxHp="1320" maxMp="2478"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="291" block="291" parry="291"
		                main_hand_attack="18" main_hand_accuracy="338" main_hand_crit_rate="1"
		                magic_accuracy="299" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 11/2009 at US Retail -->
	<player_stats class="CLERIC" level="22">
		<stats_template maxHp="1394" maxMp="2583"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="303" block="303" parry="303"
		                main_hand_attack="18" main_hand_accuracy="346" main_hand_crit_rate="1"
		                magic_accuracy="313" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 11/2009 at US Retail -->
	<player_stats class="CLERIC" level="23">
		<stats_template maxHp="1469" maxMp="2688"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="316" block="316" parry="316"
		                main_hand_attack="18" main_hand_accuracy="354" main_hand_crit_rate="1"
		                magic_accuracy="327" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 11/2009 at US Retail -->
	<player_stats class="CLERIC" level="24">
		<stats_template maxHp="1547" maxMp="2794"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="328" block="328" parry="328"
		                main_hand_attack="18" main_hand_accuracy="362" main_hand_crit_rate="1"
		                magic_accuracy="342" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 11/2009 at US Retail -->
	<player_stats class="CLERIC" level="25">
		<stats_template maxHp="1627" maxMp="2899"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="341" block="341" parry="341"
		                main_hand_attack="18" main_hand_accuracy="370" main_hand_crit_rate="1"
		                magic_accuracy="356" boost_heal="100" />
	</player_stats>

	<!-- Checked By Kamui 11/2009 at US Retail -->
	<player_stats class="CLERIC" level="26">
		<stats_template maxHp="1708" maxMp="3005"
		                power="105" health="110" agility="90" accuracy="90" knowledge="105" will="110"
		                walk_speed="1.5" run_speed="6" fly_speed="9"
		                attack_speed="1.5"
		                evasion="353" block="353" parry="353"
